default:
  image: 'php:8.1-cli-alpine'

  before_script:
    - apk update
    - apk add --no-cache libzip-dev zip autoconf build-base
    - docker-php-ext-install zip
    - pecl install -f pcov
    - docker-php-ext-enable pcov
    - scripts/install-composer
    - php bin/composer update --no-interaction --no-ansi --no-progress
    - php bin/composer bin all update --no-interaction --no-ansi --no-progress


#############################################################################
# Unit tests
#############################################################################
.unittest_template: &unittest_body
  stage: test
  script:
    - php vendor-bin/phpunit/vendor/bin/phpunit --coverage-text --colors=never
  coverage: '/^\s*Lines:\s*\d+\.\d+\%/'

unit test:8.0:
  image: 'php:8.0-cli-alpine'
  <<: *unittest_body

unit test:8.1:
  image: 'php:8.1-cli-alpine'
  <<: *unittest_body

unit test:8.2:
  image: 'php:8.2-cli-alpine'
  <<: *unittest_body


#############################################################################
# Doc examples tests
#############################################################################
.docexamples_template: &docexamples_body
  stage: test
  script:
    - php vendor-bin/behat/vendor/bin/behat -c docs/behat.yml

doc examples test:8.0:
  image: 'php:8.0-cli-alpine'
  <<: *docexamples_body

doc examples test:8.1:
  image: 'php:8.1-cli-alpine'
  <<: *docexamples_body

doc examples test:8.2:
  image: 'php:8.2-cli-alpine'
  <<: *docexamples_body

#############################################################################
# Code Quality
#############################################################################
code style:
  stage: test
  script:
    - vendor-bin/php-cs-fixer/vendor/bin/php-cs-fixer fix --diff --dry-run --show-progress=dots --using-cache=no --verbose

type check:
  stage: test
  script:
    - vendor-bin/psalm/vendor/bin/psalm --no-progress --shepherd --show-info=true --stats
