#!/bin/sh

HERE=`dirname $0`
TOPDIR=`dirname $HERE`
BINDIR="$TOPDIR/bin"

EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"

if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]
then
    >&2 echo 'ERROR: Invalid installer checksum'
    rm composer-setup.php
    exit 1
fi

test -e "$BINDIR" || mkdir -p $BINDIR
php composer-setup.php --quiet --install-dir="$BINDIR" --filename="composer"
RESULT=$?
rm -f composer-setup.php
exit $RESULT
